### PR TITLE
ssh: fix newline terminal

### LINKED ISSUE #250: Blank line terminal access
When logging in a device, an enter is required to 
 display the user@host to access it:
image

### PR DESCRIPTION
**Pull request by noreng-jg**
This closes #250.

### CODE REVIEW

File: ssh/session.go [hunk 1]
```diff
@@ -181,20 +180,19 @@ func (s *Session) connect(passwd string, session sshserver.Session, conn net.Con
...
 				if _, err = io.Copy(s.session, bufReader); err != nil {
 					logrus.WithFields(logrus.Fields{
 						"session": s.UID,
 						"err":     err,
 					}).Error("Failed to copy from stdout in pty session")
 				}
+				n, err = stdout.Read(buf)
+                if err != nil {
+                    break
+                }
```
Comment (otavio) [inline ssh/session.go:195]: I believe the code indenting is wrong. Isn't it?
